import 'package:cached_network_image/cached_network_image.dart';
import 'package:country_picker/country_picker.dart';
import 'package:elhanbly/core/local/user_preferences/user_preferences_helper.dart';
import 'package:elhanbly/core/util/validator/validator.dart';
import 'package:elhanbly/core/widgets/ui_helpers/alert_message.dart';
import 'package:elhanbly/feature/auth/complete_profile/register_imports.dart';
import 'package:elhanbly/feature/home_layout/home_layout.dart';
import 'package:elhanbly/models/general/settings_response.dart' hide Hero;
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/flutter_svg.dart';

import '../common/country_picker_cubit.dart';
import '../../../../core/navigator/named_navigator_impl.dart';
import '../../../core/consts/images.dart';
import '../../../core/services/di.dart';
import '../../../core/theme/colors/app_colors.dart';
import '../../../core/theme/theme.dart';
import '../../../core/util/utils.dart';
import '../../../core/util/validator/order_validators.dart';
import '../../../core/widgets/app_buttons/conditional_builder.dart';
import '../../../core/widgets/app_texts/app_text.dart';
import '../../../core/widgets/text_field/master_text_field.dart';
import '../../../core/widgets/ui_helpers/extensions.dart';
import 'cubit/login_cubit.dart';

part 'login_screen.dart';
part 'login_widgets/login_logo.dart';
part 'login_widgets/login_widgets.dart';
part 'login_widgets/show_country_drop_down.dart';
