import 'package:cached_network_image/cached_network_image.dart';
import 'package:country_picker/country_picker.dart';
import 'package:dio/dio.dart';
import 'package:elhanbly/models/profile/wallet/wallet_history.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/svg.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';
import 'package:intl/intl.dart';

import '../../../core/consts/images.dart';
import '../../../core/consts/strings.dart';
import '../../../core/local/user_preferences/user_preferences_helper.dart';
import '../../../core/navigator/named_navigator_impl.dart';
import '../../../core/navigator/named_navigator_routes.dart';
import '../../../core/network/repository/repository_imports.dart';
import '../../../core/services/di.dart';
import '../../../core/theme/colors/app_colors.dart';
import '../../../core/theme/theme.dart';
import '../../../core/util/launcher.dart';
import '../../../core/util/utils.dart';
import '../../../core/util/validator/validator.dart';
import '../../../core/widgets/app_bar/custom_curved_appbar.dart';
import '../../../core/widgets/app_buttons/conditional_builder.dart';
import '../../../core/widgets/app_buttons/custom_button.dart';
import '../../../core/widgets/app_buttons/master_button.dart';
import '../../../core/widgets/app_texts/app_text.dart';
import '../../../core/widgets/loader/app_loader.dart';
import '../../../core/widgets/network_img.dart';
import '../../../core/widgets/text_field/master_text_field.dart';
import '../../../core/widgets/ui_helpers/alert_message.dart';
import '../../../core/widgets/ui_helpers/app_dropdown.dart';
import '../../../core/widgets/ui_helpers/app_rating_bar.dart';
import '../../../core/widgets/ui_helpers/bottom_sheet_helper.dart';
import '../../../core/widgets/ui_helpers/extensions.dart';

import '../../auth/login/login_imports.dart';
import '../../home_layout/cubit/home_lay_out_cubit.dart';
import 'cubit/wallet_cubit/wallet_cubit.dart';
import 'pages/wallet/pages/charge_wallet_widgets.dart';
import 'package:pay/pay.dart';
import 'dart:io';

import 'pages/wallet/pages/pay.dart';

// part 'cubit/get_fav_courses/get_fav_courses_cubit.dart';
// part 'cubit/get_fav_courses/get_fav_courses_state.dart';
part 'cubit/get_profile/get_profile_cubit.dart';
part 'cubit/get_profile/get_profile_state.dart';
part 'cubit/update_profile/update_profile_cubit.dart';
part 'cubit/update_profile/update_profile_state.dart';
// part 'pages/favourite_screen/favourite_item_card.dart';
// part 'pages/favourite_screen/favourite_screen.dart';
part 'pages/favourite_screen/favourite_widgets.dart';
part 'pages/personal_data/edit_personal_data.dart';
part 'pages/personal_data/edit_phone.dart';
part 'pages/personal_data/personal_data.dart';
part 'pages/setting_pages/about_us.dart';
part 'pages/setting_pages/technical_support.dart';
part 'pages/setting_pages/terms_screen.dart';
// part 'pages/wallet/pages/charge_with_apple_screen.dart';
// part 'pages/wallet/pages/charge_with_vodafone_screen.dart';
part 'pages/wallet/wallet_screen.dart';
part 'pages/wallet/wallet_widgets.dart';
part 'profile_screen.dart';
part 'widgets/delete_btn.dart';
part 'widgets/logout_btn.dart';
part 'widgets/profile_item.dart';
